import type { Metadata } from "next";
import { Inter } from "next/font/google";
<<<<<<< Updated upstream
import Header from "./components/Header/Header";
import ThemeProvider from "./components/ThemeProvider/ThemeProvider";

=======
import Header from "../components/Header/Header";
>>>>>>> Stashed changes
import "./globals.css";
import Dashborad from "./components/Dashborad/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< Updated upstream
    <html lang="en">
      

      <body className={inter.className}>
      <ThemeProvider>
<main>
<Header/>
        {children}
</main>

      </ThemeProvider>
        </body>
    </html>
=======

 
      <body className={inter.className}>
      <Header/>
        {children}
        </body>

   
>>>>>>> Stashed changes
  );
}
